version: '3'

networks:
  app-tier:
    driver: bridge

services:

  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5433'
    volumes:
      - '${PWD}/pgdata:/temp/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=postgres'
      - 'POSTGRESQL_PASSWORD=password'
      - 'POSTGRESQL_DATABASE=job-search'
    networks:
      - app-tier


  job_search:
    restart: always
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      - 'DB_HOST=localhost'
      - 'DB_PORT=5433'
      - 'DB_NAME=job-search'
      - 'DB_PASSWORD=password'
      - 'DB_USER=postgres'
    networks:
      - app-tier



  
  